---
version: '2'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  python:
    image: python:3.5
    volumes:
      - .:/usr/src/app
      - site-packages:/usr/local/lib/python3.5/site-packages
    working_dir: /usr/src/app

volumes:
  postgres: {}
  site-packages: {}
